[package]
name = "gpgsync"
version = "0.1.0"
authors = ["Micah Lee <micah@micahflee.com>"]

[dependencies]
#openpgp = { git = "https://gitlab.com/sequoia-pgp/sequoia.git" }

[dependencies.gtk]
version = "0.4.0"
features = ["v3_16"]
